config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  root 'feeds#index'
  get 'feeds/:id/authors_publications', to: 'feeds#authors_publications', as: :authors_publications

  resources :posts, except: [:index]
  resources :pins, only: %i[create destroy] do
    member do
      patch :up_to
      patch :down_to
    end
  end
  resources :youtube, only: :show
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    sessions_index_handler

    @pins = params[:hide_pins] == '1' ? [] : current_user&.sorted_pins
    @pagy, @posts = pagy(Post.search(current_user, params),
                         items: params[:per_page] ||= 15,
                         link_extra: 'data-turbo-action="advance"')
  end

  def authors_publications
    session_author_handler

    author = User.find(params[:id])
    @pins = if params[:hide_pins] == '1'
              []
            else
              current_user&.sorted_pins&.includes(:post)&.where(post: { user_id: author.id })
            end
    @pagy, @posts = pagy(Post.where(user: author)
                             .search(current_user, params)
                             .without_user_pins(current_user),
                         items: params[:per_page] ||= 15,
                         link_extra: 'data-turbo-action="advance"')
  end

  private

  def sessions_index_handler
    session[:published] = params[:sort_by].to_s if params[:sort_by].present?
    params[:sort_by] = session[:published] || ''

    # session[:hide_draft] = params[:hide_draft].to_s if params[:hide_draft].present?
    # params[:hide_draft] = session[:hide_draft] || ''

    # session[:hide_hidden] = params[:hide_hidden].to_s if params[:hide_hidden].present?
    # params[:hide_hidden] = session[:hide_hidden] || ''

    # session[:hide_pins] = params[:hide_pins].to_s if params[:hide_pins].present?
    # params[:hide_pins] = session[:hide_pins] || ''
  end

  def session_author_handler
    session[:author_published] = params[:sort_by].to_s if params[:sort_by].present?
    params[:sort_by] = session[:author_published] || ''

    # session[:author_hide_draft] = params[:hide_draft].to_s if params[:hide_draft].present?
    # params[:hide_draft] = session[:author_hide_draft] || ''

    # session[:author_hide_hidden] = params[:hide_hidden].to_s if params[:hide_hidden].present?
    # params[:hide_hidden] = session[:author_hide_hidden] || ''

    # session[:author_hide_pins] = params[:hide_pins].to_s if params[:hide_pins].present?
    # params[:hide_pins] = session[:author_hide_pins] || ''
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_pins.html.erb
<% pins.each do |pin| %>
  <%= render partial: 'feeds/post', locals: { post: pin.post, pin: pin, author: author, user: user } %>
<% end %>

app/views/feeds/_post.html.erb
<%= render PostComponent.new(post: post, current_user: user, pin: pin, author: author) %>

app/views/feeds/_posts.html.erb
<% posts.each do |post| %>
  <%= render partial: 'feeds/post', locals: { post: post, pin: nil, author: author, user: user } %>
<% end %>

app/views/feeds/authors_publications.html.erb
  <main class="mt-4 mb-5">
    <div class="container">
      <div class="mb-4">
        <%= form_with url: authors_publications_path(id: params[:id]),
                      method: :get,
                      data: { 
                        controller: 'debounce',
                        debounce_target: 'form',
                        turbo_action: "advance",
                        turbo_frame: 'global',
                        action: 'input->debounce#search' 
                            }, class: "row align-items-center" do |f| %>

          <div class='col-2'>
            <div class='form-floating row'>
              <%= f.select :sort_by, 
                        options_for_select([['Oldest', :published_at_asc],
                                            ['Newest', :published_at_desc]],
                                            selected: session[:published]&.to_sym || :published_at_asc),
                        { }, { class: 'form-select'} %>
              <%= f.label :sort_by, t('feeds.index.sort_by') %>
            </div>
          </div>

          <div class='col-2'>
            <div class="form-check form-switch">
              <%= f.check_box :hide_draft, { class: 'form-check-input', checked: params[:hide_draft] == '1' }, 1, nil %>
              <label><%= t('feeds.index.hide_draft') %></label>
            </div>
          </div>
          <div class='col-2'>
            <div class="form-check form-switch">
              <%= f.check_box :hide_hidden, { class: 'form-check-input', checked: params[:hide_hidden] == '1' }, 1, nil %>
              <label><%= t('feeds.index.hide_hidden') %></label>
            </div>
          </div>
          <div class='col-2'>
            <div class="form-check form-switch">
              <%= f.check_box :hide_pins, { class: 'form-check-input', checked: params[:hide_pins] == '1' }, 1, nil %>
              <label><%= t('feeds.index.hide_pins') %></label>
            </div>
          </div>
          <div class='col-4'>
            <div class="input-group">
              <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
              <%= f.search_field :title, value: params[:title], placeholder: t('feeds.index.search'), class: 'form-control' %>
            </div>
          </div>
        <% end %>  
                            
      </div>
      <div class="row">
        <%= turbo_frame_tag 'global' do %>
          <%= turbo_frame_tag 'pins' do %>
            <% if user_signed_in? && current_user&.pins.present? %>
              <%= render partial: 'feeds/pins', locals: { pins: @pins, author: true, user: current_user } %>
            <% end %>
          <% end %>

          <%= turbo_frame_tag 'posts' do %>
              <%= render partial: 'feeds/posts', locals: { posts: @posts, author: true, user: current_user } %>

              <% if @pagy.pages > 1 %>
                <div class="footer text-center mt-4" id="pagy">
                  <%== pagy_nav(@pagy)%>
                </div>
              <% end %>
          <% end %>
        <% end %>
        
      </div>
    </div>
  </main>

app/views/feeds/index.html.erb
<%= turbo_stream_from :feed %>

  <main class="mt-4 mb-5">
    <div class="container">
      <div class="mb-4">
        <%= form_with url: root_path,
                      method: :get, 
                      data: { 
                        controller: 'debounce',
                        debounce_target: 'form',
                        turbo_action: "advance",
                        turbo_frame: 'global',
                        action: 'input->debounce#search' 
                            }, class: "row align-items-center" do |f| %>

        <div class='col-2'>
          <div class='form-floating row'>
            <%= f.select :sort_by, 
                      options_for_select([['Oldest', :published_at_asc],
                                          ['Newest', :published_at_desc]],
                                          selected: session[:published]&.to_sym || :published_at_asc),
                      { }, { class: 'form-select'} %>
            <%= f.label :sort_by, t('feeds.index.sort_by') %>
          </div>
        </div>

        <div class='col-2'>
          <div class="form-check form-switch">
            <%= f.check_box :hide_draft, { class: 'form-check-input', checked: params[:hide_draft] == '1' }, 1, nil %>
            <label><%= t('feeds.index.hide_draft') %></label>
          </div>
        </div>
        <div class='col-2'>
          <div class="form-check form-switch">
            <%= f.check_box :hide_hidden, { class: 'form-check-input', checked: params[:hide_hidden] == '1' }, 1, nil %>
            <label><%= t('feeds.index.hide_hidden') %></label>
          </div>
        </div>
        <div class='col-2'>
          <div class="form-check form-switch">
            <%= f.check_box :hide_pins, { class: 'form-check-input', checked: params[:hide_pins] == '1' }, 1, nil %>
            <label><%= t('feeds.index.hide_pins') %></label>
          </div>
        </div>
        <div class='col-4'>
          <div class="input-group">
            <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
            <%= f.search_field :title, value: params[:title], placeholder: t('feeds.index.search'), class: 'form-control' %>
          </div>
        </div>
        <% end %>                  
      </div>

      <hr>

      <div class="row">
        <%= turbo_frame_tag 'global' do %>
          <%= turbo_frame_tag 'pins' do %>
            <% if user_signed_in? && current_user&.pins.present? %>
              <%= render partial: 'feeds/pins', locals: { pins: @pins, author: false, user: current_user } %>
            <% end %>
          <% end %>

          <div id='posts_broadcast'>
            <%= turbo_frame_tag 'posts' do %>
                <%= render partial: 'feeds/posts', locals: { posts: @posts, author: false, user: current_user } %>

                <% if @pagy.pages > 1 %>
                  <div class="footer text-center mt-4" id="pagy">
                    <%== pagy_nav(@pagy)%>
                  </div>
                <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>
  </main>